# Server config
server.port=8080

# Application name
spring.application.name=timekeeping

# Datasource config (SQL Server)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Dion_project;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true;useUnicode=true
spring.datasource.username=sa
spring.datasource.password=P@ssw0rd
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
logging.level.org.springframework.security=DEBUG

# UTF-8 Encoding Configurations
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true
spring.http.encoding.enabled=true
spring.thymeleaf.encoding=UTF-8

# JPA & Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# SQL Initialization
spring.sql.init.mode=never
spring.sql.init.encoding=UTF-8
spring.jpa.defer-datasource-initialization=true

# DEVTOOLS
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
